### ISSUE TITLE
overflow-x: scroll, by tapping false nested element

### ISSUE THREAD

**Issue by xMarkusSpringerx** [hammerjs/hammer.js#453]
Hi guys,

i have a question.

``` html
<div id="thumbnail_navi">
 <div class="thumbnail_content">
  <div class="nailthumb-container"> <img src="pic1.jpg"></div>
  <div class="nailthumb-container"> <img src="pic2.jpg"></div>
  <div class="nailthumb-container"> <img src="pic3.jpg"></div>
  <div class="nailthumb-container"> <img src="pic4.jpg"></div>
...
 </div>
</div>
```

The id "thumbnail_navi" has the CSS-Attribute

``` css
#thumbnail_navi {
    overflow-x: scroll;
    width: 100%;
    -webkit-overflow-scrolling: touch;
    padding-top: 3px;
}

.thumbnail_content {
    width: 15000px;
    position: relative;
}

.nailthumb-container {
    float: left;
    padding: 0 0 0 5px !important;
}

```

If i swipe through the images horizontally and click on one of the items (while scrolling and the touchend event would be fired already), i get the false position of the element.

``` javascript
var position_of_id = id.position().left;
```

~~http://jsfiddle.net/amk221/6kxL2/3/~~
This snipped works for me just with a 

``` javascript
$(this).on("tap click", function(event) {
```

but not with 

``` javascript
Hammer(this).on("tap", function(event) {
```

This might help you to find a solution. t

Who can help me?

Thanks
