### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by janhocevar** [hammerjs/hammer.js#775]
I'm having this strange issue, where I'm using hammer.js library to create some responsive table functionalities.

When I'm testing the page on my iPhone (this issue is not happening on any Android device, iPhone only), the functionality works fine if I'm testing it from my local machine - I'm using Ghostlab for testing pages from local machine. However, when I deploy the code to staging server, functionality breaks. What I mean by breaks is that it works fine, but it stops working after 2 pan events. This issue is both on Chrome and Safari on iPhone.

I also opened Safari console for my phone and I'm not getting any JS errors. And I tried copying local .js file to staging server and that didn't solve the issue either.

Does anyone have an idea, why the same code isn't working on staging server but it does on local server?

**Comment by crimsonronin** [comment]
I am also experiencing this problem.

It happens when you have a scrollable element that contains a number of "off screen" items. If the elements that are initially off screen are panned to fill the screen (ie. so all elements that were initially on screen, are now off screen), no subsequent pan events are fired.

Confirmed that it's only happening on iPhone (both Chrome and Safari).

**Comment by crimsonronin** [comment]
My issue, which could be the same one experienced by @janhocevar, wasn't to do with hammer.js, but more to do with the scrollable container's css.

I had the following:

```css
.gallery {
	overflow: hidden;
	height: 200px;
	position: relative;
}
.gallery-inner {
	position: relative;
	white-space: nowrap;
	overflow: visible;
}
```

```html
<div class="gallery">
	<div class="gallery-inner" hm-panleft="onPan" hm-panright="onPan" hm-panend="onPanEnd">
		<div>1</div>
		<div>2</div>
		<div>3</div>
		<div>4</div>
		<div>5</div>
		<div>6</div>
		<div>7</div>
	</div>
</div>

```
*Note I'm using the angular adapter for hammer*


I would then use the callback functions on pan to set the `left` css value on `.gallery-inner`.

What this does is move the event area (`.gallery-inner`) off screen. This works fine on all browsers except on iPhone.

So I ended up putting in another container for the touch area, and set the `left` value on it.

eg.
```css
.gallery {
	overflow: hidden;
	height: 200px;
	position: relative;
}
.gallery-scrollable {
	position: relative;
	white-space: nowrap;
	overflow: visible;
}
```

```html
<div class="gallery">
	<div class="gallery-inner" hm-panleft="onPan" hm-panright="onPan" hm-panend="onPanEnd">
		<div class="gallery-scrollable">
			<div>1</div>
			<div>2</div>
			<div>3</div>
			<div>4</div>
			<div>5</div>
			<div>6</div>
			<div>7</div>
		</div>
	</div>
</div>

```

So now just set `left` on `.gallery-scrollable`.

I hope that helps.
